### ISSUE TITLE
Clean up menu

### ISSUE THREAD

**Issue by kaihendry** [Webconverger/Debian-Live-config#17]
![Status quo](https://cloud.githubusercontent.com/assets/765871/4299293/01a9ebc0-3e34-11e4-96c0-80da4c34f8ff.png)

Proposal: **No 486 menu** since people generally accidentally choose this or get confused between 486/686.
- Webconverger Live kiosk >
- \- Languages starting with English as default
- Neon with http://neon.webconverger.com/about/ options
- Install

**Comment by nmaas87** [comment]
How to switch to 486 mode on boot? Which option do I have to enter?
